version: "3"

services:

  mongodb:
    image: mongo:4.0.12
    ports:
      - 27018:27017
    environment:
      USER: root
      PASS: root
    volumes:
    - ./mongodata/:/data/db

  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: "redis:5"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - node.name=elastic
      - cluster.name=elastic-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - ./elasticdata:/usr/share/elasticsearch/data

  slack_bot:
    build: slackbot/
    command: python3 ./runner.py
    environment:
      - DOCKER=true
    volumes:
      - ./core/:/core/
      - ./slackbot/:/slackbot/
    depends_on:
      - rabbitmq

  api:
    build: api/
    command: python3 ./wsgi.py
    ports:
      - 5000:5000
    environment:
      - DOCKER=true
    volumes:
      - ./core/:/core/
      - ./api/:/api/
      - ./stanza_resources/:/root/stanza_resources
    depends_on:
      - elasticsearch
      - rabbitmq
      - redis
      - mongodb
      - slack_bot

  crawler:
    build: crawler/
    environment:
      - DOCKER=true
    volumes:
      - ./core/:/core/
      - ./database/:/database/
      - ./crawler/:/crawler/
      - ./stanza_resources/:/root/stanza_resources

    depends_on:
      - rabbitmq
      - mongodb
      - slack_bot
      - elasticsearch

    entrypoint: python3

volumes:
  elasticdata:
  stanza_resources:
  mongodata: